name: CI
on:
  push:
    branches: [ master, dmckinstry/actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy: 
      fail-fast: false 

    steps:
    - uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning. 
    - name: Initialize CodeQL 
      uses: github/codeql-action/init@v1 

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore src/VSTSDemoGeneratorV2.sln
 
    - name: Build and Publish Web App
      run: msbuild src/VSTSDemoGeneratorV2.sln /p:Configuration=Release /p:DeployOnBuild=true

    # Perform CodeQL analysis
    - name: Perform CodeQL Analysis 
      uses: github/codeql-action/analyze@v1
